namespace Connector.HeavyJob.v1.CostAdjustments;

using Json.Schema.Generation;
using System;
using System.Text.Json.Serialization;
using Xchange.Connector.SDK.CacheWriter;

/// <summary>
/// Data object that will represent an object in the Xchange system. This will be converted to a JsonSchema, 
/// so add attributes to the properties to provide any descriptions, titles, ranges, max, min, etc... 
/// These types will be used for validation at runtime to make sure the objects being passed through the system 
/// are properly formed. The schema also helps provide integrators more information for what the values 
/// are intended to be.
/// </summary>
[PrimaryKey("id", nameof(Id))]
//[AlternateKey("alt-key-id", nameof(CompanyId), nameof(EquipmentNumber))]
[Description("Cost adjustments for a business unit")]
public class CostAdjustmentsDataObject
{
    [JsonPropertyName("id")]
    [Description("The cost adjustment id")]
    [Required]
    public required Guid Id { get; init; }

    [JsonPropertyName("businessUnitId")]
    [Description("The business unit id")]
    [Required]
    public required Guid BusinessUnitId { get; init; }

    [JsonPropertyName("code")]
    [Description("The cost adjustment code")]
    [Required]
    public required string Code { get; init; }

    [JsonPropertyName("description")]
    [Description("The cost adjustment description")]
    public string? Description { get; init; }

    [JsonPropertyName("applyCost")]
    [Description("whether cost values (based on rates and/or entry) are generated by that cost adjustment entity")]
    public bool? ApplyCost { get; init; }

    [JsonPropertyName("applyToAllHours")]
    [Description("Whether to apply cost against attendance hours in addition to working hours")]
    public bool? ApplyToAllHours { get; init; }

    [JsonPropertyName("isTaxable")]
    [Description("Whether the cost adjustment is taxable")]
    public bool? IsTaxable { get; init; }

    [JsonPropertyName("isActive")]
    [Description("Whether the cost adjustment is active")]
    public bool? IsActive { get; init; }

    [JsonPropertyName("type")]
    [Description("The type of cost adjustment")]
    [Required]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public CostAdjustmentType Type { get; init; }

    [JsonPropertyName("accountingCode")]
    [Description("The accounting code")]
    public string? AccountingCode { get; init; }
}

public enum CostAdjustmentType
{
    Undefined,
    Hour,
    Day,
    Dollar,
    Quantity
}